---
# pb.generate.variables.yaml
# This playbook file has 1 role:
# roles/generate_vpns: generates the variables required for provisioning and testing

- name: Generate variables
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - generate_vpns
