# playbooks/host_vars/SGN/intf.yaml
system:
  - interface: lo0
    description: "Loopback"
    family:
      - type: inet
        address: 2.2.2.2/32
      - type: iso
        address: 49.0001.1001.0202.0202.00
  - interface: ge-0/0/1
    vlanid: 100
    description: "Uplink interface"
    family:
      - type: inet
        address: 172.16.1.2/24
      - type: iso
      - type: mpls
protocols:
  bgppeers:
    - 1.1.1.1
    - 3.3.3.3
