---
# roles/build_config/tasks/main.yaml
# This YAML file aggregates all the config parts and builds a single config file per router
# Completed files are placed in the 'config' folder (folder is create if it doesnt exist).

- name: Check if directory {{ junos_conf_dir }} is present
  file: path={{ junos_conf_dir }} state=directory
  run_once: true

- name: Assembling configurations and copying to config/
  assemble: src={{ build_dir }} dest={{ junos_conf }}
