system:
  - interface: lo0
    description: "Loopback"
    family:
      - type: inet
        address: 1.1.1.1/32
      - type: iso
        address: 49.0001.1001.0101.0101.00
  - interface: ge-0/0/1
    vlanid: 100
    description: "Uplink interface"
    family:
      - type: inet
        address: 172.16.1.1/24
      - type: iso
      - type: mpls
protocols:
  bgppeers:
    - 2.2.2.2
    - 3.3.3.3
